version: "3.7"
services:
  dev:
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN:-0000000000000000000000000000000000000000}
        USER: ${USER:-user}
        USER_ID: ${UID:-1000}
        GROUP: ${USER:-user}
        GROUP_ID: ${UID:-1000}
    environment:
      DOCKER_HOST: tcp://host.docker.internal:2375
      GITHUB_TOKEN: ${GITHUB_TOKEN:-0000000000000000000000000000000000000000}
      DISPLAY: host.docker.internal:0
      TERM: xterm-256color